import Link from 'next/link';
import './styles/navbar.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul className="nav-links">
            <li>
              <Link href="/">
                <div className="nav-link">Home</div>
              </Link>
            </li>
            <li>
              <Link href="/all-projects">
                <div className="nav-link">Projects</div>
              </Link>
            </li>
            <li>
              <Link href="/contact-me">
                <div className="nav-link">Contact Me</div>
              </Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}