import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <nav>
          <ul>
            <li>
              <Link href="/">
                <div>Home</div>
              </Link>
            </li>
            <li>
              <Link href="/all-projects">
                <div>Projects</div>
              </Link>
            </li>
            <li>
              <Link href="/contact-me">
                <div>Contact Me</div>
              </Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  )
}
